language: python
python:
    - 3.6
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pycodestyle

jobs: 
  include:
  - stage: pycodestyle
    python: 3.6
    script: find . -name \*.py -exec pycodestyle --ignore=E402 {} +

stages:
  - pycodestyle