language: python
python:
- 3.6
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install --upgrade pip
- pip install --upgrade pip
- pip install pycodestyle pylint
- pip install twine setuptools wheel
- pip install -r requirements.txt

jobs:
  include:
  - stage: linters
    name: pylint
    python: 3.6
    script: find . -name \*.py -exec pylint  {} +
  - script: find . -name \*.py -exec pycodestyle --ignore=W503 {} +
    name: pycodestyle
  - stage: tests
    python: 3.6
    script: python test.py $PLANIFNEIGE_SIM_API_KEY
  - stage: deploy
    python: 3.6
    script:
      - python3 setup.py sdist bdist_wheel
      - python3 -m twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD

stages:
- linters
- tests
- name: deploy
  on: 
    tags: true
    branch: master


env:
  global:
  - secure: TPvHfG0cQQPB2YSItBg+fABHhT1y60Fc2fXADMcs2ZWpCF79kznDkeZlSObcR5FfCnSLA98kjW7Ula6iP14AVPUtuCfZvSS6vo6+kgwx73AU6tuQQ3GShITxClaNZ7vDcwtuGqf7NQAxqKmCEdHSXKvwStvj860gqVA1Fi0EJY7XHOs6awBHxMxCFNz4+MWhF3nzS3WgapyYlKiis3zBU91XYtAyY4cHMUCLrCtM86yiLs54MNfBq7RoG0m6sfFlpMuYSbPUq1lDIIUtczQRf5LWn89GNgTrl1vVPgPdH7l2RUWhbmZ7eIPaPr9/0XNF4qNclYdsGAeGj6PLO9RysCFQrqOX4/VDACc4fcLHMXvctndldueEpT7fMwnkb6ie+ee+0bvtLqa03PYfCg7Aslyk8LFwHNc5JRqmL1gZYO5iQOdGRvsBqZjSOK5h8X9BtU7JuCLKADivRLiDbCELeRjVvOt5D4BXeOvAuFbteEZ+CzKT+ePNvkpUZSqBmr8bz7yIPY8FZNef63fj3wz7Zqto1KU/qkYXdaezGgZp+O86HBbNqX5ILwo0kGZn2r+KwSIvazsRCRGUvOIpEaKxDZVXRWdesQbawtCTAxcFYca7tEaQUsu1aZVb4qaGGi01o289yoGozPnYlHdwWmIGbwxPDN23jtifdQxmc5oe8FA=
  - secure: TdQ9NuDeX1tWfNeC4Wzs/ST1BEiyPKBK0doxCgVm7KFyw7ufpWP9yJ8LCvlv8MQN6o/6KkYG39bO/I4woMjlOaAOTvp2RLFhvJTJ8ikLt2tF4Zg8ZwJymZjHRUsn/bXpqw4qTDJFPWzCygA73fzZU16jNMSXJvq/UmznXS/w/9TnsE6hr2SJjlFvMMy/rzaXrsAGCKDvbzJ8Ag+iR9Gsi1fBnvFVOJZ9jpcvdB4PBAyXNV5fqLOXwkRCab13Hz/hz7RQHM/+OxmSTyIyypbDD+7unSTnen3SbMfzx2iVMeFlcQLaD4rIl2HGniKy6B4pmWWjvl45+1WUOdenA+qAbo0zsUjaEMa/Cx901LlaCX2jUotuXva1Dr8EZKGtmJvlx9tiOagmbMqfaBdlV8A42edq8pQ2OVy2kP/LBBdXtDHJGgLQCuKOPufOsOyaLeVfqwjxDdBfvK9XH1BpKAYoEDC8S2ReEttoERqKN2ARo3+kw2WjMCksK+GljjFomZqeUzGReClIqjSBjpuP1B/ndKNDvjsE4mY6Qr3PCNz1D7F2MUBPRTkgaASMOSA0WkrIeNerKz7SA3Xo3hJiX6ML/eJbzvD3oYGtjlv8TiqMsaqAWd1L64oF4l1/KViVwmZHMl9q5ZDWN/F0WHRv1w1As7esmlc65hJSbXckUMJPpSA=
  - secure: WARoSjKKWSeacL9wTU4+C4BMeZiW2AZbH9fWyfZKb785Tmis5AF4pp8Vl+TwUs3BsXhGdi0M0IiUtPWI0+FqXdxnqbEMrM6iUlE5+Tz/QkXa6xWb0Rr7f7lqIWYDTsbawXAIf6tZ1zM9BPL0TBQpksgvG+7VY7XppgJEw9rlr8OyIbshguzQC6ZwPicquMdEvUXUCc8l8Zb7Gy661gkNuEKcUqKXMByRjTbXTQzQLhzGJcKDaXvT+FjkMOAkJEoMcm1Z0cGbmDSExVsiAmDghwd5mrI6+21xRCRmyLamw3tHzqFJRvwEfSK+sHuGZUtalNGoKNcTUZrwIKuz6P0tgUnMG2lEId5NGgY9AkVhk1cSyTmjK+z5fAEM3A/K94YihPV+RpanlKmpUBaRsFP5uEywLb19Ar25Rqkyw55Wt1CvUrlcg1Y+C1u/kmlEg14tB6vTqQYIlleL2AqdS1u84TSPUfIhAeCHPa0lYIVysB9+ypnlduRtOVlfx79qo94GuX4XH9GRCzuyJzv3zg7xlL8M+/4gUuiw7BizJlp3JocakO8/ydlaGjcLmmE1KtPA2T040iyfp/S1GiHetNtJJDecvRPJCRZwAPp7a5dcaMIwRpZMk7UmN51fpwt0Bp1hO1++AQPa2wlmBkFvjPqz/uWnw3AW9OMJKvHdoXOfJl8=
